When a Mule app starts, a connectivity test runs on components such as the HTTP or FTP connector that connects to an external server. If the test fails, the default behavior logs a warning message and continues with the deployment of the app instead of blocking the deployment.

To modify the default behavior, there are several actions you can take depending on when you attempt to reconnect. For an initial failure, you can set a number of reconnection attempts. When all connections attempts fail, you can force the deployment to fail. To reconnect without limits, you can set an interval to attempt reconnection retries repeatedly. 

* Reconnect (`reconnect`): Limits the number of reconnection attempts and the interval to execute them. For example, you can set a count of 5 reconnection attempts at a frequency of every 4000 milliseconds (ms) and defaults to 2 reconnection attempts at a frequency of 2000 ms.
* Fail Deployment (`failsDeployment`): Forces the deployment to fail if the connection fails and all configured reconnection attempts are exhausted. The example below fails after 5 reconnection attempts:
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----
* Reconnect Forever (`reconnect-forever`): Attempts to reconnect at a given interval without limits on the number of retries because there is no value for a specified count. For example, you can set the frequency to every 4000 ms while the app runs and default to every 2000 ms. The example below does not set a limit on the number of reconnection attempts:
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000"/>
  </reconnection>
</http:request-connection>
----
